runtime: nodejs14
env: standard
instance_class: F1
service: pakoman-digital-loan-web

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic